Repository Mbed-TLS/mbedtls-test, pull requests merged in 2022-04, with the labels that each got.

#42 Enable FreeBSD test on OpenCI
  vars/environ.groovy
Labels: approved

#41 Use the host MAKEFLAGS variable in containers
  vars/common.groovy
Labels: bug, size:S, approved

#40 Introduce caching for base images and intermediate steps of docker image builds
  vars/gen_jobs.groovy
Labels: size:S
