Repository Mbed-TLS/mbedtls-test, pull requests merged in 2022-11, with the labels that each got.

#68 Add stage declaration for Result analysis phase
  vars/mbedtls-release-Jenkinsfile
  vars/mbedtls.groovy
Labels: bug, approved

#67 Report parallel errors to Github early
  vars/mbedtls.groovy
Labels: enhancement, approved

#71 Only consider pushes, manual CI runs and reviews as "PR activity" for the purposes of nightly builds
  vars/mbedtls.groovy
Labels: approved

#72 Upload a failure list as a Jenkins artifact
  vars/analysis.groovy
  vars/gen_jobs.groovy
Labels: enhancement, size-s, single-reviewer, approved
