Repository Mbed-TLS/mbedtls-test, pull requests merged in 2023-10, with the labels that each got.

#124 Add mechanism to override Python requirements
  resources/docker_files/arm-compilers/Dockerfile
  resources/docker_files/ubuntu-20.04/Dockerfile
  vars/checkout_repo.groovy
  vars/common.groovy
  vars/gen_jobs.groovy
  vars/mbedtls.groovy
  vars/scripts.groovy
Labels: size-s, approved, priority-high

#129 Restrict automatic runs of PR jobs
  vars/common.groovy
  vars/mbedtls.groovy
Labels: bug, needs: ci, security, size-s, approved, priority-high

#131 Restore logic for tests skipped in merge queue
  vars/mbedtls.groovy
Labels: bug, regression, single-reviewer, approved, priority-high, size-xs

#130 Prevent deadlock in api-abi-checking job
  vars/gen_jobs.groovy
Labels: bug, needs: review, regression, single-reviewer, priority-high, size-xs

#114 Only gather branch information once per job
  src/org/mbed/tls/jenkins/BranchInfo.groovy
  vars/checkout_repo.groovy
  vars/common.groovy
  vars/gen_jobs.groovy
  vars/mbedtls.groovy
Labels: enhancement, needs: ci, size-s, approved

#122 Use version numbers in $OPENSSL and $GNUTLS variables; add OpenSSL 3.0 and 3.1
  resources/docker_files/ubuntu-16.04/Dockerfile
  resources/docker_files/ubuntu-18.04/Dockerfile
  resources/docker_files/ubuntu-20.04/Dockerfile
  resources/docker_files/ubuntu-22.04/Dockerfile
Labels: needs: ci, size-s, approved, priority-medium
