Repository Mbed-TLS/mbedtls-test, pull requests merged in 2023-07, with the labels that each got.

#112 Add xxd for data file regenerating tests
  resources/docker_files/ubuntu-16.04/Dockerfile
  resources/docker_files/ubuntu-18.04/Dockerfile
  resources/docker_files/ubuntu-20.04/Dockerfile
  resources/docker_files/ubuntu-22.04/Dockerfile
Labels: needs: ci, approved, size-xs

#113 Add hexdump command
  resources/docker_files/ubuntu-16.04/Dockerfile
  resources/docker_files/ubuntu-18.04/Dockerfile
  resources/docker_files/ubuntu-20.04/Dockerfile
  resources/docker_files/ubuntu-22.04/Dockerfile
Labels: needs: ci, approved

#118 Add earliest and latest compilers
  resources/docker_files/README.md
  resources/docker_files/ubuntu-16.04/Dockerfile
  resources/docker_files/ubuntu-22.04/Dockerfile
Labels: enhancement, size-s, approved, priority-medium
