Repository Mbed-TLS/mbedtls-test, pull requests merged in 2024-01, with the labels that each got.

#144 speed up analyze-outcomes stage
  vars/analysis.groovy
Labels: enhancement, approved, priority-high, size-xs

#154 Fix generation of failures.csv when there are only non-outcome failures
  vars/analysis.groovy
Labels: bug, approved, priority-high

#155 Drop MSVC 2015 testing from nightly builds
  vars/common.groovy
Labels: bug, single-reviewer, approved, size-xs, priority-very-high
