Repository Mbed-TLS/mbedtls-test, pull requests merged in 2025-05, with the labels that each got.

#205 Update GCC 15 snapshot to the 15.1.0 release
  resources/docker_files/ubuntu-22.04/Dockerfile
Labels: approved, priority-high, size-xs

#203 Switch MSVC builds to Visual Studio 2017
  resources/windows/windows_testing.py
  vars/common.groovy
  vars/gen_jobs.groovy
  vars/scripts.groovy
Labels: approved, priority-medium, size-xs

#201 Checkout from GitHub only once per branch, stash and then just unstash
  src/org/mbed/tls/jenkins/BranchInfo.groovy
  vars/analysis.groovy
  vars/checkout_repo.groovy
  vars/common.groovy
  vars/gen_jobs.groovy
  vars/mbedtls.groovy
Labels: approved

#208 Fix API-ABI checks on fast-forward mergeable PRs
  vars/gen_jobs.groovy
Labels: approved, size-xs
